### ISSUE TITLE
harness generate

### ISSUE THREAD

**Issue by mineechor** [sslab-gatech/winnie#46] opened 2022-11-10 08:22 UTC
Hello, since I am new to fuzz, can you give me more details about harness generation? And I don't know how can I get the harness.dll？
{`afl-fuzz -i in -o out -t 1000 -I 1000 -- -bbfile basicblocks.bb -- -harness harness.dll -no_minidumps -- toy_example.exe @@`)
Thank you very much!

**Comment by william31212** [comment] 2022-11-19 19:28
I have the same problem.

**Comment by william31212** [comment] 2022-11-20 12:23
@mineechor 
I found the some article with build harness.dll generation
https://hackyboiz.github.io/2021/08/22/fabu1ous/winnie-2/

**Comment by mineechor** [comment] 2022-11-21 05:36
> @mineechor I found the article building harness.dll https://hackyboiz.github.io/2021/08/22/fabu1ous/winnie-2/

Thank you very much！！

**Comment by mineechor** [comment] 2022-11-21 05:38
@william31212 Thank you very much！！

**Comment by mineechor** [comment] 2022-11-24 07:35
@maybe via the email？18783122766@163.com

**Comment by mineechor** [comment] 2022-11-24 07:56
@william31212 I’am confused about harness.cpp generation. In fact, I am interested in the three python files(synthesizer.py、syn-multi.py、dominator.py) and library_trace.cpp.

**Comment by william31212** [comment] 2022-11-24 08:02
@mineechor I have sent an email to you. However, I'm researching this repo's code, and maybe cannot answer your question.
But we can discuss it together?

**Comment by mineechor** [comment] 2022-11-24 08:02
@william31212 ok

**Comment by gdynamics** [comment] 2022-12-03 23:44
This issue should be closed, as it is a duplicate of #43 . Of note, the first author of the paper said he was working on a write-up there, so updates on the effort will most likely be posted there.

**Closed** 2022-12-05 04:34 UTC
